@HOST = http://localhost:3333 

GET {{HOST}}/candidate HTTP/1.1
Content-Type: application/json 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM1MWMzYzgzLTUzNWQtNDVkNy04MzE0LTc1MmY0YzFhOWM2MSIsIm5hbWUiOiJNb2lzZXMgTHVjYXMiLCJlbWFpbCI6Im1vaXNlc0BnbWFpbC5jb20iLCJ0eXBlIjoiUiIsImVudGVycHJpc2VOYW1lIjoiVGVjIFNBIiwiaWF0IjoxNjk3OTIzNjU3fQ.XQn0Sx8yOEta67yi1fv7KuJ1iVHCu0IcfgZfYTI6enM