@HOST = http://localhost:3333

POST {{HOST}}/job HTTP/1.1
Content-Type: application/json 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ2NWY4ZjQ1LWNiNTMtNGVhNS1hMWM0LTIwMjczOGEwYTIzOSIsIm5hbWUiOiJNb2lzZXMgTHVjYXMiLCJlbWFpbCI6Im1vaXNlc3NAZ21haWwuY29tIiwidHlwZSI6IlIiLCJlbnRlcnByaXNlTmFtZSI6IlRlYyBTQSIsImlhdCI6MTY5ODgwNDc5OX0.LqPnLgQ1pSSr72P2eJ7YXEZLjT6YYSIiaO_-a8aKr2I
# description: string;
# enterprise: string;
# limitDate: Date;
# isActive: boolean;
# maxCandidates?: number (opcional);

{
    "description": "Vaga Junior HTML, CSS",
    "enterprise": "Growdev SA",
    "limitDate": "2023-11-01 22:30",
    "isActive": true
}