@HOST = http://localhost:3333

POST {{HOST}}/application/bc2f68d4-d09a-4a14-836d-be80a426445f HTTP/1.1
Content-Type: application/json 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNhNzg1MmU3LWQ1ZjgtNGE0Mi05YzZkLWVjNWQxNGZmZTg1NiIsIm5hbWUiOiJNYXJpYSBMdXJkZXMiLCJlbWFpbCI6Im1hcmlhQGdtYWlsbC5jb20iLCJ0eXBlIjoiQyIsImVudGVycHJpc2VOYW1lIjpudWxsLCJpYXQiOjE2OTgwNjE0OTR9.EddPHb08CgQn6VAlz3_k1n7_VUs7Eka6U-aRASZZDek