@HOST = http://localhost:3333 

GET {{HOST}}/application/job HTTP/1.1
Content-Type: application/json 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUwZGY2ODBiLTMxZWEtNDZkYS1iODA1LTZkN2QwMDY5MTg1YSIsIm5hbWUiOiJNYXJpYSBMdXJkZXMiLCJlbWFpbCI6Im1hcmlhQGdtYWlsLmNvbSIsInR5cGUiOiJDIiwiZW50ZXJwcmlzZU5hbWUiOm51bGwsImlhdCI6MTY5NzgwNzM3Mn0.9vWQ4mr1cuFBOV2Nv47cqU4O-cT4lN3qj3Dnac2Vjsg